version: "3"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://gitea:3000
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "22:22"

networks: 
  default: 
    external: 
      name: gitea-net