version: "3"

services:
  drone-agent:
    image: drone/drone-runner-docker:latest
    environment:
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca7
      - DRONE_RUNNER_NETWORKS=gitea-net
    command: agent
    restart: always
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

networks: 
  default: 
    external: 
      name: gitea-net